data:
  csv_file_path: ./data/imdb-dataset.csv
  test_set_ratio: 0.3
  train_csv_save_path: ./data/train.csv
  test_csv_save_path: ./data/test.csv

features:
  vectorizer: count-vectorizer
  train_features_save_path: ./result/train.joblib
  test_features_save_path: ./result/test.joblib

train:
  penalty: l2
  C: 1.0
  solver: lbfgs
  max_iter: 10000
  model_save_path: ./result/model.joblib

evaluate:
  metric: accuracy
  results_save_path: ./result/evaluate_results.yaml
  
